### ISSUE TITLE
New features request: execution provisioners

### ISSUE THREAD

**Issue by VictorNuzhdin** [elsudano/terraform-provider-vmworkstation#13] opened 2024-02-28 13:01 UTC
Hi, @elsudano :) 
Are there any plans to implement provisioning functionality 
as is implemented in the Terraform cloud-providers, 
like provisioner "remote-exec" and provisioner "local-exec"?

For example:

```
## Remote execute provisioner
provisioner "remote-exec" {

  #..ssh connection section
  connection {
    type = "ssh"
    user = "VM_SYSTEM_USER"
    host = "VM_IP_ADDRESS"
    agent = true
    timeout = "3m"
  }

  #..remote commands execution section
  inline = [
    "echo Hello",
    "echo World",
  ]
}

## Local execute provisioner
provisioner "local-exec" {
  
  #..auto execute this command locally after VM created/cloned
  command = "ansible-playbook -i VM_IP_ADDRESS -u VM_SYSTEM_USER ./ansible/auto-configure.yml"
}
```

Thanks)

**Comment by VictorNuzhdin** [comment] 2024-03-01 12:27
@elsudano , Hi :)

First of all, thanks for releasing version v1.0.4. 
It really fixes the errors and now everything works more or less well on Windows 10 22H2
(but there are some problems that can be solved by external scripts)

About my request for new features.. 

As a result of the tests I carried out, it turned out 
that the "local-exec" provisioner works out of the box in Terraform.

We just inject this "provisioner" section inside the resource section and that’s it -
everything is working without external extra features ))
See example below.

```
terraform {
  required_providers {
    vmworkstation = {
      source  = "elsudano/vmworkstation"
      version = "1.0.4"
    }
  }
  required_version = ">= 0.15.4"
}
provider "vmworkstation" {
  user     = var.vmws_user
  password = var.vmws_password
  url      = var.vmws_url
  https    = false
  debug    = true
}

  ##..injecting provisioner section
  provisioner "local-exec" {
    command = "echo local_exec_provisioner_test > provisioner_test.log"
  }
```
I haven't tested the "remote-exec" provisioner yet, 
but I think it will work. 

The only problem that will need to be solved here
is to launch the VM after it is created with Terraform,
so that you can connect to it via ssh
:)

**Comment by elsudano** [comment] 2024-03-01 12:40
> @elsudano , Hi :)
> 
> First of all, thanks for releasing version v1.0.4. It really fixes the errors and now everything works more or less well on Windows 10 22H2 (but there are some problems that can be solved by external scripts)
> 
> About my request for new features..
> 
> After several tests it became obvious that the "local-exec" provisioner works out of the box in Terraform.
> 
> We just inject this "provisioner" section inside the resource section and that’s it - everything works without external extra features )) See example below.
> 
> ```
> terraform {
>   required_providers {
>     vmworkstation = {
>       source  = "elsudano/vmworkstation"
>       version = "1.0.4"
>     }
>   }
>   required_version = ">= 0.15.4"
> }
> provider "vmworkstation" {
>   user     = var.vmws_user
>   password = var.vmws_password
>   url      = var.vmws_url
>   https    = false
>   debug    = true
> }
> 
> resource "vmworkstation_vm" "vmw1" {
> 
>   sourceid     = var.vmw_source_vm_id
>   denomination = var.vmw_target_vm_name
>   description  = var.vmw_target_vm_descr
>   processors   = var.vmw_target_vm_cpu_num
>   memory       = var.vmw_target_vm_ram_mb
>   path        = "${var.vmw_target_vm_default_path}\\${var.vmw_target_vm_name}\\${var.vmw_target_vm_name}.vmx"
> 
>   ##..injecting provisioner section
>   provisioner "local-exec" {
>     command = "echo local_exec_provisioner_test > provisioner_test.log"
>   }
> }
> ```
> 
> I haven't tested the "remote-exec" provisioner yet, but I think it will work.
> 
> The only problem that will need to be solved here is to launch the VM after it is created with Terraform, so that you can connect to it via ssh :)

Thanks for test it, Yep I was googling and as you mention, isn't need by the provider to that part work properly.

Apart from that, I'm working in that part about of the VM start automatically after created, in order to lunch the remote-exec when the instance is created

moreover, about of the issues that you resolved with external scripts, could you tell me more about that? just in case that I should take a look in order to resolve.

Again, thanks for test it

**Comment by VictorNuzhdin** [comment] 2024-03-01 13:13
@elsudano , ok, I tried to explain..

When I was make tests I encountered errors when reapplying terraform config after being destroyed.

```
terraform destroy
terraform validate; terraform plan; terraform apply -auto-approve
```
As a result of investigating the problem, 
it was found that the "terraform-vmware" provider 
incorrectly performs the "terraform destroy" operation 
and leaves some garbage.



..not finished yet

**Comment by elsudano** [comment] 2024-03-01 13:24
> @elsudano , ok, I tried to explain..
> 
> When I was make tests I encountered errors when reapplying terraform config after being destroyed.
> 
> ```
> terraform destroy
> terraform validate; terraform plan; terraform apply -auto-approve
> ```
> 
> As a result of investigating the problem, it was found that the "terraform-vmware" provider incorrectly performs the "terraform destroy" operation and leaves some garbage.
> 
> ..not finished yet

yep, I know, is a know issue, the problem is in the API of VMWare, if you try this steps you will understand:

Form the browser try to reach the API of the VmWare Workstation and then try to create a VM, then try to register this VM in the UI of Workstation, and then try to DELETE the instance, You will see, that the Instance that you have in the UI don't disappear after to DELETE, but the instance isn't there, so you need remove manually the instance form the UI and then run again the Terraform plan and then apply.

As I said, is a API issue, because, I suppose If I want to delete the instance, I want to delete of the UI as well, but the API still in the UI and I don't know why.

moreover if you try to found one API method to unregister the Instance from the UI doesn't exit in the API, so I can't unregister the instance with TF neither

**Comment by VictorNuzhdin** [comment] 2024-03-01 13:55
@elsudano 

> As I said, it's an API issue because I always assume that if I want to delete the instance, 
> I also want to remove it from the user interface, but the API keeps the instance in the user interface, and I don't know why.

I ended my comment above :)

And I also noticed that you need to restart the VMware REST service
C:\Program Files (x86)\VMware\VMware Workstation\vmrest
so that it re-reads the configuration (for example, when we want to change the default path)

I didn't understand this right away, and spend lots of time
for trying to change  VMs default directory, constantly getting an error something like "path not found"

:)

**Comment by VictorNuzhdin** [comment] 2024-03-01 13:57
@elsudano 

I think we can close this Issue because there is nothing more to say here
:)

**Comment by elsudano** [comment] 2024-03-01 14:43
Perfect, thanks for the feedback

**Closed by elsudano** 2024-03-01 14:43 UTC
